login: &login
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


development:
  database: typo_dev
  <<: *login

test:
  database: typo_tests
  <<: *login

production:
  database: typo
  <<: *login
